#! /bin/sh

bspc monitor eDP-1 -d I II III IV

bspc config border_width            2
bspc config window_gap              6
bspc config top_padding             0 # Works with wm-restack = bspwm

bspc config split_ratio             0.50
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_follows_pointer   true

bspc config normal_border_color '#303446'
bspc config active_border_color '#303446'
bspc config focused_border_color '#babbf1'
bspc config presel_feedback_color '#babbf1'

bspc rule -a zoom state=floating
