#! /bin/sh

bspc monitor eDP-1 -d I II III IV

bspc config border_width            2
bspc config window_gap              6
bspc config top_padding             20

bspc config split_ratio             0.50
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_follows_pointer   true

bspc config normal_border_color '#2E3440'
bspc config active_border_color '#2E3440'
bspc config focused_border_color '#EBCB8B'
bspc config presel_feedback_color '#EBCB8B'

bspc rule -a zoom state=floating
